# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: StepBuddy iOS CI

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Xcode version
        run: xcodebuild -version

      - name: Available simulators
        run: xcrun simctl list devices available

      - name: Build
        run: |
          xcodebuild \
            -project stepbuddy.xcodeproj \
            -scheme stepbuddy \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Test
        run: |
          xcodebuild \
            -project stepbuddy.xcodeproj \
            -scheme stepbuddy \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            CODE_SIGNING_ALLOWED=NO \
            test
